# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1aa09ff6f1f6111839a315a11b4bae27ce601a97f3930f5376268c9faf93e09e4c3fa49e7ec52d88c7fae8c00479757d0e59894857f6642e95979afff283377

test:
  secret_key_base: 5f19bdcf1fac569e771417f7bb204011c131ad2fc0b9b7ddfebdd2004c32e1c7c34bfb02ebd1d1fb1f01f6e7e6c5dbde0066da6584f3e77f82f646ce96259f35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
